name: Run tests and send results to Allure TestOps

on:
  push:
    branches:
      - main

jobs:
  run_all_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://testing.qatools.cloud
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 1878

      - name: Run tests via allurectl
        run: |
          allurectl launch create --project-id 1878 --launch-name "GitHub Actions Run" --launch-tags "CI"
          allurectl run pytest tests/ --alluredir=build/allure-results
        env:
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURE_ENDPOINT: https://testing.qatools.cloud
          ALLURE_PROJECT_ID: 1878
          ALLURE_RESULTS: build/allure-results

      - name: Upload results to Allure TestOps
        if: always()
        run: allurectl upload build/allure-results
        env:
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURE_ENDPOINT: https://testing.qatools.cloud
          ALLURE_PROJECT_ID: 1878
