name: TestOps Demo

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "TestOps service parameter for launch ID."
        required: false
      ALLURE_USERNAME:
        description: "TestOps service parameter for user identity."
        required: false
      Branch:
        description: "Branch or Tag to run on."
        required: true
        default: 'main'
      ALLURE_LAUNCH_ID:
        description: "Launch ID for filtering (optional)."
        required: false
      ALLURE_LAUNCH_NAME:
        description: "Launch name for filtering (optional)."
        required: false

env:
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN_FOR_SELFHOSTED }}
  ALLURE_ENDPOINT: https://testing.qatools.cloud
  ALLURE_PROJECT_ID: 1878
  ALLURE_RESULTS: build/allure-results

  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_USERNAME: ${{ github.event.inputs.ALLURE_USERNAME }}
  ALLURE_LAUNCH_ID: ${{ github.event.inputs.ALLURE_LAUNCH_ID }}
  ALLURE_LAUNCH_NAME: ${{ github.event.inputs.ALLURE_LAUNCH_NAME }}

jobs:
  # -----------------------------------------------------------------
  # JOB 1: УСПЕШНЫЙ И ПРОВАЛЕННЫЙ СТАТУСЫ (БЫСТРЫЕ ТЕСТЫ)
  # -----------------------------------------------------------------
  run_allure_tests_part1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.Branch }}

      - name: Setup Python, Install dependencies, Setup AllureCTL
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
          allure-token: ${{ env.ALLURE_TOKEN }}
          allure-project-id: ${{ env.ALLURE_PROJECT_ID }}

      - name: Run Job 1 (Success and Failed)
        run: |
          mkdir -p "${ALLURE_RESULTS}/part1"
          # Запуск Тестов 1 и 2 (УСПЕШНЫЙ и ПРОВАЛЕННЫЙ) - они БЫСТРЫЕ в Python-коде
          allurectl watch -- pytest tests/test_payment.py::test_login_for_payment tests/test_payment.py::test_add_product_to_cart --alluredir="${ALLURE_RESULTS}/part1"

  # -----------------------------------------------------------------
  # JOB 2: НЕИЗВЕСТНЫЙ СТАТУС (ДОЛГИЕ ТЕСТЫ, БУДУТ ПРЕРВАНЫ)
  # -----------------------------------------------------------------
  run_allure_tests_part2:
    runs-on: ubuntu-latest
    needs: run_allure_tests_part1 # Запускается после Job 1
    timeout-minutes: 0.25 # <--- Таймаут в 15 секунд, чтобы прервать долгие тесты
    steps:
      # Повторяем Setup, так как это отдельная Job
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.Branch }}
      - name: Setup Python, Install dependencies, Setup AllureCTL
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
          allure-token: ${{ env.ALLURE_TOKEN }}
          allure-project-id: ${{ env.ALLURE_PROJECT_ID }}
      
      - name: Run Job 2 (Unknown Status)
        run: |
          mkdir -p "${ALLURE_RESULTS}/part2"
          # Запуск Тестов 3, 4, 5 (НЕИЗВЕСТНЫЙ) - они ДОЛГИЕ (sleep 10s) в Python-коде
          # Job будет прервана по таймауту, пока allurectl watch ждёт их завершения
          allurectl watch -- pytest tests/test_payment.py::test_checkout_from_cart tests/test_payment.py::test_select_payment_method tests/test_payment.py::test_confirm_payment --alluredir="${ALLURE_RESULTS}/part2"
